# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='bot_class_name',
            field=models.CharField(default='SampleBot', max_length=32),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='bot_module_name',
            field=models.CharField(default='bots.base_bot', max_length=32),
        ),
    ]
