# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20171024_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='bot_module_name',
            field=models.CharField(default='base_bot', max_length=32),
        ),
    ]
