# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171021_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openfireuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
